apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: rabbit
  ports:
    - name: rabbitmq2-amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq2-web
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: LoadBalancer
